<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateEmailsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        // IMPORTANT
        Schema::create('emails', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('organization_id')->unsigned();
            $table->string('name')->nullable();
            $table->string('role')->nullable();
            $table->string('email');
            $table->string('type');
            $table->string('description');
            $table->boolean('rfc_validation');
            $table->boolean('no_rfc_validation');
            $table->boolean('dns_check');
            $table->boolean('free_email_provider');
            $table->boolean('disposable_email_provider');
            $table->boolean('role_or_business_email');
            $table->boolean('spoof_check');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('emails');
    }
}
